### ISSUE TITLE
Pantries Class Ingredients Stock

### ISSUE THREAD

**Issue by npdarrington** [npdarrington/Whats-Cookin#17]
As a user, I want to be able to see see all of the ingredients in my pantry and how much of that ingredient I have in stock.

- [x] Create a method that will show a user their ingredient pantry and how many of each ingredient they have.

**Comment by hannakim91** [comment]
- This function `findPantryInfo()` currently lives in scripts.js -- Ashley and I are thinking we should have a `Pantry` Class + test
- Currently tied to DOM manipulation: need to refactor and isolate class method portion

**Comment by npdarrington** [comment]
Definitely sounds like the better option. The rubric says that every user should have a pantry, however having user contain methods that control what the happens with the pantry feels like a violation of SRP.
