### ISSUE TITLE
Pantry Class Ingredients Stock: show when not enough ingredients 

### ISSUE THREAD

**Issue by npdarrington** [npdarrington/Whats-Cookin#19]
As a user, I want to be able to see when I don't have enough ingredients to cook a given meal

- [ ] Create a method that will show a user when they don't have enough ingredients to cook a meal they have selected.

**Comment by aemcdonald** [comment]
This method doesn't exist yet. Need to create it & perhaps it could exist in a Pantry class?

**Comment by hannakim91** [comment]
work in progress: need to find number of items -- see issue #68 that needs to be resolved too
