### ISSUE TITLE
Pantry Class Ingredients To Buy Cost

### ISSUE THREAD

**Issue by npdarrington** [npdarrington/Whats-Cookin#23]
As a user, when the app tells me that I need to buy more ingredients for a given meal, I want to be able to see how much it will cost in order to buy the needed quantity for that recipe.

- [ ] Create/modify a method that will show the user the total cost of the ingredients they need to buy to cook an ingredient.

**Comment by aemcdonald** [comment]
this method does not yet exist & could belong in a potential pantry class?
I'm noticing issue #19, #21 & this current issue all have similar functionality that could be utilized within 1 DOM function

**Comment by hannakim91** [comment]
There's a commented out method in `Recipe` class that may be a good starting off point for calculating costs of missing ingredients too
