### ISSUE TITLE
Pantry Class Add Ingredients To My Pantry

### ISSUE THREAD

**Issue by npdarrington** [npdarrington/Whats-Cookin#25]
As a user, I want to have the app add the necessary ingredients that I need to cook a recipe in my pantry automatically.

- [ ] Create a method that will automatically keep track of the recipes ingredients and add it into their pantry.
- use fetch to keep up to date with database

**Comment by aemcdonald** [comment]
Maybe this functionality should exist on a "grocery list" that we create for the user?
- maybe this method should first check the pantry ingredients 
- then add to a "grocery list" the ingredients that they are lacking in their pantry?

**Comment by hannakim91** [comment]
I think the word "automatically" is adding some confusion from the spec req's:

How I am interpretting it:
- When a user "cooks" recipe (which could be a button on the DOM) and doesn't have enough ingredients, display for user shows what ingredients are missing (which is found on feature #21)
- A user clicks another button ("Add Missing Ingredients to Pantry") - which thereby "automatically" adds the ingredients to the pantry -- now this recipe can be "cooked" #27

---
The "grocery list" you're talking about sounds like something that could be a potential extension feature -- user doesn't automatically get new items added to pantry but instead the grocery list
