### ISSUE TITLE
Pantry Class Remove Ingredients Once Recipe Cooked

### ISSUE THREAD

**Issue by npdarrington** [npdarrington/Whats-Cookin#27]
As a user, I want the app to automatically remove the ingredients that were used in a recipe when I have cooked it.

- [ ] Create a method that will keep track of removing ingredients from the pantry when a user has flagged that recipe as being cooked.

**Comment by aemcdonald** [comment]
this method does not yet exist, perhaps a Pantry class would be the best place for it?
