### ISSUE TITLE
Pantry Ingredients In Pantry DOM

### ISSUE THREAD

**Issue by npdarrington** [npdarrington/Whats-Cookin#29]
As a user, I want to be able to see how many ingredients I have inside of my pantry when I have selected a specific meal to cook.

- [x] Create a page (modal?) when a user has clicked on a recipe that shows them the specific of the recipe and when they have enough ingredients to cook it.

**Comment by hannakim91** [comment]
DOM/user interface to incorporate Pantry functionality for user TBD
