### ISSUE TITLE
Pantry method: pantry has enough ingredients to cook a meal

### ISSUE THREAD

**Issue by hannakim91** [npdarrington/Whats-Cookin#31]
Determine the amount of ingredients still needed to cook a given meal, based on what’s in my pantry

- [ ] Create a method (or add onto previous method) that returns number of each ingredient needed to cook a meal (aka not currently in pantry)

**Comment by aemcdonald** [comment]
This method seems to be related to the method we are creating on issue #19 where the method will "show a user when they don't have enough ingredients to cook a meal they have selected."

**Comment by hannakim91** [comment]
sorry Ashley - made duplicate cards for Pantry from mis-hearing Nathan say he stopped at a certain point
