### ISSUE TITLE
Refactor: Use Inheritance

### ISSUE THREAD

**Issue by hannakim91** [npdarrington/Whats-Cookin#46]
Discuss how we might want to refactor classes 

- Identify redundant code in your classes and opportunities for DRYing it up
- Refactor within your classes to create dynamic methods that use arguments/parameters for changing their behavior
- Refactor across your classes to create a parent class that others inherit methods from as appropriate OR be able to defend your choice for not using inheritance.

**Comment by aemcdonald** [comment]
After discussing the pros and cons of using inheritance & a check-in with our instructors, we have decided that using inheritance would not provide any large benefit to our overall class structure.
