### ISSUE TITLE
Bug with Testing

### ISSUE THREAD

**Issue by aemcdonald** [npdarrington/Whats-Cookin#53]
- when running npm test, receive 2 errors that say: 
- Error in ./test/recipe-test.js
  Module not found: '../data/recipe-data' in '/Users/ashleymcdonald/turing/mod2projects/Whats-Cookin/test'

- Error in ./test/user-test.js
  Module not found: '../data/users-data' in '/Users/ashleymcdonald/turing/mod2projects/Whats-Cookin/test'

**Comment by npdarrington** [comment]
This seems to be an intended error. The file structure has the data folder within /src. Changing them to ../src/data/users-data and same for recipe will fix it.
